import os
import traceback
import csv
from reportlab.lib import colors, pagesizes
from reportlab.platypus import (
    SimpleDocTemplate, Frame, Paragraph, Image, PageTemplate, FrameBreak,
    Spacer, Table, TableStyle, NextPageTemplate, PageBreak
)
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from typing import Annotated
from ..data_source.WeatherAnalysisInsights import WeatherAnalysisInsights


class ReportWeatherLabUtils:
    def save_generated_report(
        location: Annotated[str, "Geographical location for the weather analysis"],
        text: Annotated[str, "Text generated by the Weather Analyst containing weather analysis, crop recommendations and all reasoning data."],
        save_path: Annotated[str, "Folder Path where the text file will be saved."]
    ) -> None:
        """
        Saves the generated weather analysis report as a .txt file in the specified location.
        """
        textfile_path = os.path.join(save_path, f"{location}_Weather_Analysis_Report.txt")
        os.makedirs(os.path.dirname(textfile_path), exist_ok=True)
        try:
            with open(textfile_path, "w", encoding="utf-8") as file:
                file.write(text)
            print(f"Report successfully saved at: {textfile_path}")
        except Exception as e:
            print(f"Error saving report: {e}")
        
    def build_weather_analysis_report(
        location: Annotated[str, "Geographical location for the weather analysis"],
        save_path: Annotated[str, "Folder Path to save the weather analysis PDF"],
        text: Annotated[str, "Structured summary of Text generated by the Weather Analyst containing weather analysis and crop recommendations."],
#         rainfall_data_text: Annotated[
#             str, 
#             "a paragraph of text: Summary of rainfall sum variations over the analyzed period."
#         ],
#         temperature_trends_text: Annotated[
#             str, 
#             "a paragraph of text: Summary of temperature variations over the analyzed period."
#         ],
#         precipitation_analysis_text: Annotated[
#             str, 
#             "a paragraph of text: Analysis of rainfall patterns, heavy precipitation periods, and trends"
#         ],
#         extreme_events_text: Annotated[
#             str, 
#             "a paragraph of text: Occurrences of extreme weather events like storms, heatwaves, or floods"
#         ],
#         generated_insights_text: Annotated[
#     str, 
#     """a paragraph of text: Comprehensive reasoning and analysis on historical weather data, focusing on rainfall and temperature trends. The AI agent will evaluate seasonal patterns, drought or flood risks, and temperature fluctuations to determine their impact on agriculture. Making predictions on agricultural crop Suitability.
#     """
# ],
        year: Annotated[str, "Year when the weather analysis was performed"]
    ) -> str:
        """
        Aggregates rainfall data summary, temperature trend summary, precipitation analysis, comprehensive reasoning and analysis of weather and prediction of crop suitability into a PDF report.
        """
        try:
            # Setup PDF page properties
            page_width, page_height = pagesizes.A4
            margin = 4

            # Define PDF output path
            pdf_path = os.path.join(save_path, f"{location}_Weather_Analysis_Report.pdf")
            os.makedirs(os.path.dirname(pdf_path), exist_ok=True)
            doc = SimpleDocTemplate(pdf_path, pagesize=pagesizes.A4)

            # # Define frames for layout
            # frame_left = Frame(margin, margin, page_width * 2 / 3 - margin * 2, page_height - margin * 2, id="left")
            # frame_right = Frame(page_width * 2 / 3, margin, page_width / 3 - margin * 2, page_height - margin * 2, id="right")

            # single_frame = Frame(margin, margin, page_width - margin * 2, page_height - margin * 2, id="single")

            # page_template = PageTemplate(id="TwoColumns", frames=[frame_left, frame_right])
            # single_column_layout = PageTemplate(id="OneCol", frames=[single_frame])
            # doc.addPageTemplates([page_template, single_column_layout])
            # Define page margins and full-width frame
            single_frame = Frame(
                margin,                      # x
                margin,                      # y
                page_width - 2 * margin,     # width
                page_height - 2 * margin,    # height
                id="SingleColumn"
            )
            
            # Apply only the single-column layout
            single_column_layout = PageTemplate(id="OneCol", frames=[single_frame])
            doc.addPageTemplates([single_column_layout])

            # Define styles
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(name="Title", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=16, leading=20, alignment=TA_LEFT, spaceAfter=10)
            subtitle_style = ParagraphStyle(name="Subtitle", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=14, leading=12, alignment=TA_LEFT, spaceAfter=6)
            body_style = ParagraphStyle(name="Body", parent=styles["Normal"], fontName="Helvetica", fontSize=10, alignment=TA_JUSTIFY)

            # Content for PDF
            content = []
            content.append(Paragraph(f"Weather Analysis Report: {location}", title_style))
            content.append(Paragraph(f"Analysis Year: {year}", body_style))

            content.append(Paragraph("AI-Generated Insights", subtitle_style))
            content.append(Paragraph(text, body_style))
            
            content.append(Paragraph("Rainfall Data Summary", subtitle_style))
            # content.append(Paragraph(rainfall_data_text, body_style))
            # content.append(Paragraph(precipitation_analysis_text, body_style))

            rainfall_filename = f"rainfall_{location.replace(' ', '_')}_{year}.csv"
            rainfall_csv_path = os.path.join(save_path, rainfall_filename)
            with open(rainfall_csv_path, 'r') as file:
                reader = csv.reader(file)
                rainfall_data = [row for row in reader]
             # Step 3: Create Table and style
            rainfall_table = Table(rainfall_data)
            style = TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),  # Header background
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),      # Header text
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),             # Center alignment
                ('GRID', (0, 0), (-1, -1), 1, colors.black),       # Add grid lines
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),   # Bold header
                ('FONTSIZE', (0, 0), (-1, -1), 10),                # Font size
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),            # Header padding
            ])
            rainfall_table.setStyle(style)
            content.append(rainfall_table)

            content.append(Paragraph("Temperature Data Summary", subtitle_style))
            # content.append(Paragraph(temperature_trends_text, body_style))
            # content.append(Paragraph(extreme_events_text, body_style))

            temperature_filename = f"temperature_{location.replace(' ', '_')}_{year}.csv"
            temperature_csv_path = os.path.join(save_path, temperature_filename)
            with open(temperature_csv_path, 'r') as file:
                reader = csv.reader(file)
                temp_data = [row for row in reader]
             # Step 3: Create Table and style
            temperature_table = Table(temp_data)
            temperature_table.setStyle(style)
            content.append(temperature_table)
            
            # content.append(Paragraph("Generated Insights", subtitle_style))
            # content.append(Paragraph(generated_insights_text, body_style))

            # Generate PDF
            doc.build(content)
            return f"Weather Analysis Report generated successfully: {pdf_path}"

        except Exception:
            return traceback.format_exc()


    def build_structured_analysis_report(
        location: Annotated[str, "Geographical location for the weather analysis"],
        save_path: Annotated[str, "Folder Path to save the weather analysis PDF"],
        analysis: Annotated[WeatherAnalysisInsights, "Structured insights on rainfall, temperature, crop suitability, and predictions"],
        year: Annotated[str, "Year when the weather analysis was performed"]
    ) -> str:
        """
        Aggregates rainfall data summary, temperature trend summary, precipitation analysis,
        comprehensive reasoning and analysis of weather, and prediction of crop suitability into a PDF report.
        """
        try:
            # Setup PDF page properties
            page_width, page_height = pagesizes.A4
            margin = 4
    
            # Define PDF output path
            pdf_path = os.path.join(save_path, f"{location}_Weather_Analysis_Report.pdf")
            os.makedirs(os.path.dirname(pdf_path), exist_ok=True)
            doc = SimpleDocTemplate(pdf_path, pagesize=pagesizes.A4)
    
            # # Define frames for layout
            # frame_left = Frame(margin, margin, page_width * 2 / 3 - margin * 2, page_height - margin * 2, id="left")
            # frame_right = Frame(page_width * 2 / 3, margin, page_width / 3 - margin * 2, page_height - margin * 2, id="right")
            # single_frame = Frame(margin, margin, page_width - margin * 2, page_height - margin * 2, id="single")
    
            # page_template = PageTemplate(id="TwoColumns", frames=[frame_left, frame_right])
            # single_column_layout = PageTemplate(id="OneCol", frames=[single_frame])
            # doc.addPageTemplates([page_template, single_column_layout])
            single_frame = Frame(
                margin,                      # x
                margin,                      # y
                page_width - 2 * margin,     # width
                page_height - 2 * margin,    # height
                id="SingleColumn"
            )
            
            # Apply only the single-column layout
            single_column_layout = PageTemplate(id="OneCol", frames=[single_frame])
            doc.addPageTemplates([single_column_layout])
    
            # Define styles
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(name="Title", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=16, leading=20, alignment=TA_LEFT, spaceAfter=10)
            subtitle_style = ParagraphStyle(name="Subtitle", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=14, leading=12, alignment=TA_LEFT, spaceAfter=6)
            body_style = ParagraphStyle(name="Body", parent=styles["Normal"], fontName="Helvetica", fontSize=10, alignment=TA_JUSTIFY)
    
            # Content for PDF
            content = []
            content.append(Paragraph(f"Weather Analysis Report: {location}", title_style))
            content.append(Paragraph(f"Analysis Year: {year}", body_style))
    
            # Insert structured analysis sections
            content.append(Paragraph("Analysis of Rainfall Trends", subtitle_style))
            content.append(Paragraph(analysis.Analysis_of_Rainfall_Trends, body_style))
            
            content.append(Paragraph("Analysis of Temperature", subtitle_style))
            content.append(Paragraph(analysis.Analysis_of_Temperature, body_style))
            
            content.append(Paragraph("Crop Suitability & Crop Growth Requirements", subtitle_style))
            content.append(Paragraph(analysis.Crop_Suitability_and_Crop_Growth_Requirements, body_style))
            
            content.append(Paragraph("Predictive Insights of Weather", subtitle_style))
            content.append(Paragraph(analysis.Predictive_Insights_of_weather, body_style))

            content.append(PageBreak())
    
            # Rainfall Table
            content.append(Paragraph("Rainfall Data Summary", subtitle_style))
            rainfall_filename = f"rainfall_{location.replace(' ', '_')}_{year}.csv"
            rainfall_csv_path = os.path.join(save_path, rainfall_filename)
            if os.path.exists(rainfall_csv_path):
                with open(rainfall_csv_path, 'r') as file:
                    reader = csv.reader(file)
                    rainfall_data = [row for row in reader]
                rainfall_table = Table(rainfall_data)
                style = TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ])
                rainfall_table.setStyle(style)
                content.append(rainfall_table)
    
            # Temperature Table
            content.append(Paragraph("Temperature Data Summary", subtitle_style))
            temperature_filename = f"temperature_{location.replace(' ', '_')}_{year}.csv"
            temperature_csv_path = os.path.join(save_path, temperature_filename)
            if os.path.exists(temperature_csv_path):
                with open(temperature_csv_path, 'r') as file:
                    reader = csv.reader(file)
                    temp_data = [row for row in reader]
                temperature_table = Table(temp_data)
                temperature_table.setStyle(style)
                content.append(temperature_table)
    
            # Build the PDF
            doc.build(content)
            return f"Weather Analysis Report generated successfully: {pdf_path}"
    
        except Exception:
            return traceback.format_exc()
